feat: support `--shell` argument
JoelEinbinder/bisect-chrome pull request #4
Opened 2022-01-31 19:48 UTC by aslushnikov

This lets us use `npx bisect-chrome --good XXX --bad YYY --shell "npm run ctest"

2022-01-31 19:53 UTC, JoelEinbinder commented on index.js
> -  const spawner = scriptPath.endsWith('.js') ? fork : spawn;
this line should already be doing what you want with no need for `--shell`

2022-01-31 19:54 UTC, JoelEinbinder commented on index.js
> -      PUPPETEER_EXECUTABLE_PATH: revisionInfo.executablePath,
and you deleted my wonderful environment variables :(

2022-01-31 19:59 UTC, JoelEinbinder commented on index.js
> -      PUPPETEER_EXECUTABLE_PATH: revisionInfo.executablePath,
oh I guess they are up above

2022-01-31 20:00 UTC, JoelEinbinder requested changes
I think the current code just works for you based on the file extension. Feel free to change the docs to clear up your confusion though.

2022-01-31 20:03 UTC, JoelEinbinder commented on README.md
> +Note: the script exposes Chromium executable path as \`CRPATH\` environment variabble.
```suggestion
Note: The Chromium executable path is exposed to the script as the \`CRPATH\` environment variable.
```

2022-01-31 20:05 UTC, JoelEinbinder approved these changes

2022-01-31 20:05 UTC, merged

2022-02-03 12:40 UTC, mxschmitt commented
Amazing feature!